-- 게시판테이블
CREATE TABLE BOARD(
   BID INT PRIMARY KEY,
   TITLE VARCHAR(100) NOT NULL,
   WRITER VARCHAR(20) NOT NULL,
   MID VARCHAR(20) NOT NULL,
   CONTENT VARCHAR(1000) NOT NULL,
   VIEWS INT DEFAULT 0,
   REGDATE DATE DEFAULT SYSDATE,
   UPLOADFILE VARCHAR(100) NOT NUll
);

SELECT * FROM BOARD;
DROP TABLE BOARD;