-- 회원 테이블
CREATE TABLE MEMBER(
   MID VARCHAR(20) PRIMARY KEY,
   MPW VARCHAR(20) NOT NULL,
   NAME VARCHAR(20) NOT NULL,
   ROLE VARCHAR(10) NOT NULL,
   PENALTY INT DEFAULT 0
);

INSERT INTO MEMBER VALUES('admin','1234','관리자','ADMIN');
INSERT INTO MEMBER VALUES('timo','1234','작은 티모','MEMBER');

SELECT * FROM MEMBER;
DROP TABLE MEMBER;