-- 댓글테이블
CREATE TABLE REPLY(
   RID INT PRIMARY KEY,
   BID INT NOT NULL,
   MID VARCHAR(20) NOT NULL,
   RNAME VARCHAR(20) NOT NULL,
   RCONTENT VARCHAR(1000) NOT NULL,
   RREPORT INT DEFAULT 0,
   RBLIND INT DEFAULT 0
);

SELECT * FROM REPLY;
DROP TABLE REPLY;